### ISSUE TITLE
Issue with installing qber: error for flask (OS: Windows 10)

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/wp4-csdh-api#12]
File "C:\Python27\lib\site-packages\flask\exth
    raise ImportError('No module named %s' % ful
ImportError: No module named flask.ext.socketio

PS C:\Users\Ruben\Git\wp4-csdh-api\src> pip install flask.ext.socketio
Collecting flask.ext.socketio
  Could not find a version that satisfies the requirement flask.ext.socketio (from versions: )
No matching distribution found for flask.ext.socketio

I did run requirements and installed the relevant packages (Flask, flask-socketio, Flask-Bootstrap, flask-swagger, rdflib, gevent, iribaker, python-magic, pandas, js2py) and Visual C++ for Windows. But now we run into this error:

PS C:\Users\Ruben\Git\wp4-csdh-api\src> python run.py
C:\Python27\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio
 instead.
  .format(x=modname), ExtDeprecationWarning
_cffi__x14a33f6ax54cebdac.c
C:\Python27\lib\site-packages\magic__pycache___cffi__x14a33f6ax54cebdac.c(208) : fatal error C1083: Cannot open include file: 'magic.h
': No such file or directory
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import socketio, app
  File "C:\Users\Ruben\Git\wp4-csdh-api\src\app__init__.py", line 62, in <module>
    import views
  File "C:\Users\Ruben\Git\wp4-csdh-api\src\app\views.py", line 20, in <module>
    import util.file_client as fc
  File "C:\Users\Ruben\Git\wp4-csdh-api\src\app\util\file_client.py", line 7, in <module>
    import magic
  File "C:\Python27\lib\site-packages\magic__init__.py", line 1, in <module>
    from . import ffi
  File "C:\Python27\lib\site-packages\magic\ffi.py", line 27, in <module>
    ext_package="magic")
  File "C:\Python27\lib\site-packages\cffi\api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 113, in load_library
    self._compile_module()
  File "C:\Python27\lib\site-packages\cffi\verifier.py", line 210, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 62, in _build
    raise VerificationError('%s: %s' % (e.__class__.**name**, e))
cffi.ffiplatform.VerificationError: CompileError: command 'C:\Users\Ruben\AppData\Local\Programs\Common\Microsoft\Visual C++ for
 Python\9.0\VC\Bin\cl.exe' failed with exit status 2
PS C:\Users\Ruben\Git\wp4-csdh-api\src>

**Comment by RubenSchalk** [comment]
The same issue occurs with the brach 1.0.0-beta (windows 10):

raise VerificationError('%s: %s' % (e.**class**.**name**, e))
cffi.ffiplatform.VerificationError: CompileError: command 'C:\Users\Ruben\AppData\Local\Programs\Common\Microsoft
\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2

**Comment by RinkeHoekstra** [comment]
… that’s a different issue. It’s because your C compiler complains.

**Comment by RubenSchalk** [comment]
Is there a way to solve this? I have tried setting the environment on 64 bit but that does not work.
